# Generated by Django 3.2.19 on 2023-05-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='state',
            new_name='is_done',
        ),
    ]
